<?php
/**
* @file
* Convert an image to CMYK with imagemagick
*/

/**
 * Implements hook_image_effect_info().
 *
 * TODO: check wether current image library is imagemagick
 */
function imagemagick_cmyk_image_effect_info() {
    $effects = array(
        'imagemagick_cmyk' => array(
            'label' => t('Convert to CMYK'),
            'help' => t('Convert this image to CMYK: basically needed when you want an image to be downloaded and used in print'),
            'effect callback' => 'imagemagick_cmyk_convert',
            'dimensions passthrough' => TRUE,
        ),
    );

    return $effects;
}

/**
 * Effect callback for the conversion to CMYK
 */
function imagemagick_cmyk_convert(&$image, $data) {
    // icc profile of original image
    $op  = "-profile ".drupal_get_path("module","imagemagick_cmyk")."/sRGB.icc";
    // icc profile of target image
    $op .= " -profile ".drupal_get_path("module","imagemagick_cmyk")."/ISOcoated_v2_300_eci.icc";

    $image->ops[] = $op;
    return TRUE;
}